title: Data for disability
subtitle: Explore data for and about disabled people in Aotearoa
description: A site with open data, tools, and resources for disabled people in Aotearoa.
analytics: false
# analytics is a boolean value that determinees whether the woopra file is enabled.

# collections are groups of pages/posts that can be displayed in blocks on the homepage and the sidebar menu.
collections:
  topics-people:
    output: true
  topics-wellbeing:
    output: true
  topics-health:
    output: true
  topics-education:
    output: true
  topics-biz:
    output: true
  topics-countries:
    output: true

markdown: kramdown

sass:
    style: compressed

include:
  - .htaccess
  - assets/css/main.scss

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md